language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_True
  user: jdsmithwes
  password:
    secure: FhW1LSIteotMq/ofIq9S6v8WFdJg9SDAV6xc9mA1NOCRCyjJRND2OnzGrm25Fqcz9i4PsoW78/1nl/YBk7xqz6xOqAuQFHFY4pTukiX3Mu2gMZdbMkSEclte+SQkLQdY7pleOwcA3DeA+gzyiQbXVl7qoCpGZxXJueau9QLVgCDzHhCaR6mAJk+RF6Bt5iM9QYSYisnQryFoeILn4KRVRm85XCZKd53+BFV47LtLhcp2XrBZSZwZo0mqj1OpjtwhdA9W5pT7zKVcQ4OttuDoBOoxfbXo6jzttkRF+hq99ml2zbZq+7HqBCkDZGd6dODT51QN6qDphzEF4yj+YRr2SvNM5vlh6TbWRDK1F6DQGX2zHGVjZEcuJwN5+wyslvmN1ZkFCRVbMiDcsRuJuFAEz2lG/t/F2c4yOGeH8qw/8SlQqAnMNWpU68zsg5AfyM9XJp14wERc6r1S7J7c9VlCO9A/MRXgTc+dcr7cAh/eo0y2OVFb+LPCHrpJR3D4pynuPsZ3fodlvrCpewMOd+YygBR4KU/WuDHBIHI5METezCpP9DWpICo92m/sRwLWvAPUIdvbmzyXmVETTdxQrbzXORk1D77uzK6+LsJVhjrt81z0/sqgFEiL4W54vhGfeJ5HeJRr3ik/8lFVGGOpceI5cDF+p/OveD6TcTKynZOLvpk=
  on:
    repo: jdsmithwes/JDSPackage
    python: 3.8
    #tag: True
